config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Read all task
  get 'tasks', to: 'tasks#index'
  # read one specific task
  get 'tasks/:id', to: 'tasks#show', as: :task
  # create>>> Post the Form
  post 'tasks', to: 'tasks#create'
  # Get the form
  get 'task/new', to: 'tasks#new', as: :new
  # Update a task with get
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  # Update a task with patch
  patch 'tasks/:id', to: 'tasks#update'
  # delete a task
  delete 'task/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  # Show with id
  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit task</h1>
  <%= form_for(@task) do |t| %>
    <div class="form-group">
      <strong><%= t.label :title %></strong>
      <%= t.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <strong><%= t.label :details %></strong>
      <%= t.text_field :details, class: 'form-control' %>
    </div>

    <div class="form-check">
      <%= t.check_box :completed, class: 'form-check-input' %>
      <%= t.label :completed, "Done", class: 'form-check-label' %></span>
    </div>

    <div class="input"><%= t.submit class: 'btn btn-primary' %></div>
  <% end %>
  <div class="border-top mt-2">
    <div class="back-link">
      <i class="fas fa-redo"></i><span><%= link_to "  Back to list", tasks_path %></span>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>
  <ul>
  <% @tasks.each do |task| %>
   <!-- If completed? show the chec icon as done -->
   <li>
     <% if task.completed %>
     <i class="fa fa-check-square" aria-hidden="true"></i>
     <% else %>
     <i class="fa fa-times" aria-hidden="true"></i>
     <% end %>
      <%= link_to task.title, task_path(task) %>

      <%= link_to destroy_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fas fa-trash"></i>
            <% end %>


    </li>
  <% end %>
</ul>
  <div class="border-top">
    <div class="back-link">
      <i class="fas fa-plus"></i>
      <span><%= link_to "Add a new task", new_path %>
      </span>
    </div>
  </div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New task</h1>
  <%= form_for(@task) do |t| %>
    <div class="form-group">
      <strong><%= t.label :title %></strong>
      <%= t.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <strong><%= t.label :details %></strong>
      <%= t.text_field :details, class: 'form-control' %>
    </div>

    <div class="input"><%= t.submit class: 'btn btn-primary' %></div>
  <% end %>
  <div class="border-top mt-2">
    <div class="back-link">
      <i class="fas fa-redo mt-2"></i><span><%= link_to "  Back to list", tasks_path %></span>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="header">
    <h1><%= @task.title %></h1>
    <div class="alert alert-dark">
      <i class="fas fa-edit"></i><span><%= link_to "  Update task", edit_path %></span>
    </div>
  </div>
  <div class="task-details">
    <p class="alert alert-secondary" role="alert"><%= @task.details %></p>
    <% if @task.completed %>
      <div><i class="fas fa-thumbs-up"></i><span>  This task is complete</span></div>
    <% else %>
      <div><i class="fas fa-thumbs-down"></i><span>  This task has not been completed yet</span></div>
    <% end %>
  </div>
  <div class="border-top">
    <div class="back-link">
      <i class="fas fa-redo mt-2"></i><span><%= link_to "  Back to list", tasks_path %></span>
    </div>
  </div>
</div>